version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://circly_user:circly_password@db:5432/circly_db
      - SECRET_KEY=your-super-secret-jwt-key-here-change-in-production
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./circly-app
    ports:
      - "19006:19006"  # Expo Metro
      - "8081:8081"    # Expo dev tools
    environment:
      - EXPO_PUBLIC_API_URL=http://localhost:8000/v1
    volumes:
      - ./circly-app:/app
      - frontend_node_modules:/app/node_modules
    command: npx expo start --web

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=circly_db
      - POSTGRES_USER=circly_user
      - POSTGRES_PASSWORD=circly_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://circly_user:circly_password@db:5432/circly_db
      - REDIS_URL=redis://redis:6379/0
    command: celery -A app.tasks worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
  backend_node_modules:
  frontend_node_modules: