"""add voter_id to votes table for god mode

Revision ID: 14903dfffd85
Revises: 8816145500c0
Create Date: 2026-01-03 23:29:12.127230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14903dfffd85'
down_revision: Union[str, Sequence[str], None] = '8816145500c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first (for existing data compatibility)
    op.add_column('votes', sa.Column('voter_id', sa.UUID(), nullable=True))

    # Step 2: For existing votes without voter_id, delete them (dev environment)
    # In production, you might want to handle this differently
    op.execute("DELETE FROM votes WHERE voter_id IS NULL")

    # Step 3: Make column non-nullable
    op.alter_column('votes', 'voter_id', nullable=False)

    # Step 4: Create index and foreign key
    op.create_index(op.f('ix_votes_voter_id'), 'votes', ['voter_id'], unique=False)
    op.create_foreign_key('fk_votes_voter_id', 'votes', 'users', ['voter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_votes_voter_id', 'votes', type_='foreignkey')
    op.drop_index(op.f('ix_votes_voter_id'), table_name='votes')
    op.drop_column('votes', 'voter_id')
    # ### end Alembic commands ###
