"""add is_orb_mode to users

Revision ID: 1985f846af23
Revises: 14903dfffd85
Create Date: 2026-01-04 19:52:38.567043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1985f846af23'
down_revision: Union[str, Sequence[str], None] = '14903dfffd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_orb_mode', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_orb_mode')
    # ### end Alembic commands ###
