"""add notification settings to users

Revision ID: 6e393d8896f8
Revises: 1985f846af23
Create Date: 2026-01-10 14:42:37.175849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e393d8896f8'
down_revision: Union[str, Sequence[str], None] = '1985f846af23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_poll_started', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_poll_reminder', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_poll_ended', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_vote_received', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_circle_invite', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_circle_invite')
    op.drop_column('users', 'notify_vote_received')
    op.drop_column('users', 'notify_poll_ended')
    op.drop_column('users', 'notify_poll_reminder')
    op.drop_column('users', 'notify_poll_started')
    # ### end Alembic commands ###
