"""create polls tables

Revision ID: de9545f81b89
Revises: 88fffa2c6e9b
Create Date: 2025-12-13 14:27:17.056058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de9545f81b89'
down_revision: Union[str, Sequence[str], None] = '88fffa2c6e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_templates',
    sa.Column('category', postgresql.ENUM('APPEARANCE', 'PERSONALITY', 'TALENT', 'SPECIAL', name='template_category'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('circle_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', name='poll_status'), server_default='ACTIVE', nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['poll_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_circle_id'), 'polls', ['circle_id'], unique=False)
    op.create_index(op.f('ix_polls_creator_id'), 'polls', ['creator_id'], unique=False)
    op.create_index(op.f('ix_polls_template_id'), 'polls', ['template_id'], unique=False)
    op.create_table('poll_results',
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vote_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_result')
    )
    op.create_index(op.f('ix_poll_results_poll_id'), 'poll_results', ['poll_id'], unique=False)
    op.create_index(op.f('ix_poll_results_user_id'), 'poll_results', ['user_id'], unique=False)
    op.create_table('votes',
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('voter_hash', sa.String(length=64), nullable=False),
    sa.Column('voted_for_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_for_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'voter_hash', name='uq_poll_voter')
    )
    op.create_index(op.f('ix_votes_poll_id'), 'votes', ['poll_id'], unique=False)
    op.create_index(op.f('ix_votes_voted_for_id'), 'votes', ['voted_for_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voted_for_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_poll_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_poll_results_user_id'), table_name='poll_results')
    op.drop_index(op.f('ix_poll_results_poll_id'), table_name='poll_results')
    op.drop_table('poll_results')
    op.drop_index(op.f('ix_polls_template_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_creator_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_circle_id'), table_name='polls')
    op.drop_table('polls')
    op.drop_table('poll_templates')
    # ### end Alembic commands ###
